version: '3.8'

services:
  
  redisgraph:
    image: "redislabs/redisgraph"

    # command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
     - "6379:6379"


    environment:
     - REDIS_REPLICATION_MODE=master

    networks:
      default:
        aliases:
          - test_redis_graph
